version: "3.9"

services:
  start-up-manager:
    build:
      context: .
      dockerfile: Dockerfile
    image: start-up-manager
    container_name: start-up-manager
    environment:
      - DB_PG_HOST=db
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    restart: unless-stopped
    ports:
      - '3000:3000'
    working_dir: /start-up-manager
    depends_on:
      - db
    command: sh -c "/wait && npm run start"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432